from airflow_dags.open_elections.load_by_state import StateMetadata

COUNTY_VOTE_PKS = ['election_id', 'precinct', 'party', 'candidate']

COUNTY_VOTES_COLS = ['notes',
                       'votes',
                       'winner',
                       'write-in']

PRECINCT_VOTE_PKS = ['election_id', 'county', 'party', 'candidate']

PRECINCT_VOTE_COLS = ['candidate name',
                      'candidate_id',
                      'candidate_name',
                      'candidate_party',
                      'candidateid',
                      'central_count',
                      'choice',
                      'choice_name',
                      'choice_order',
                      'contest',
                      'contest_id',
                      'contest_name',
                      'contest_order_id',
                      'contest_total',
                      'contest_type',
                      'contestid',
                      'contestorderid',
                      'contesttitle',
                      'count',
                      'county',
                      'done',
                      'early',
                      'early_tsx',
                      'early_tsx_fle',
                      'early_votes',
                      'early_votes_ds200',
                      'early_voting',
                      'early_voting_tsx',
                      'election_day',
                      'fle_tsx',
                      'fle_vc',
                      'flw_tsx',
                      'flw_vc',
                      'jurisdiction',
                      'late_early_votes',
                      'late_early_voting',
                      'notes',
                      'number',
                      'over_votes',
                      'overvote',
                      'party name',
                      'party_id',
                      'party_name',
                      'polling',
                      'polling_place_votes',
                      'polling_place_votes_ds200',
                      'precinct_designation',
                      'precinct_designation.1',
                      'precinct_id',
                      'precinct_name',
                      'precinct_order',
                      'precinctid',
                      'precinctname',
                      'processed_done',
                      'processed_started',
                      'provisional',
                      'provisional_votes',
                      'race',
                      'race_id',
                      'record_type',
                      'referendum_flag',
                      'subjurisdiction',
                      'tc_tsx',
                      'tc_vc1',
                      'tc_vc2',
                      'tsx',
                      'under_votes',
                      'undervote',
                      'vote_for_value',
                      'vote_total',
                      'vote_type',
                      'vote_type_id',
                      'voteforvalue',
                      'votes',
                      'votes_allowed',
                      'votetype',
                      'winner',
                      'write-in',
                      'write_in',
                      'write_ins']

VOTE_COUNT_COLS = ['votes']

metadata = StateMetadata(None,
                         'al',
                         VOTE_COUNT_COLS)
