CREATE TABLE ref_state (
    STATE_ID smallint NOT NULL PRIMARY KEY,
    DIVISION_ID smallint NOT NULL,
    STATE_NAME character varying(100),
    STATE_CODE character varying(2),
    STATE_ABBR character varying(2),
    STATE_POSTAL_ABBR character varying(2),
    STATE_FIPS_CODE character varying(2),
    STATE_PUB_FREQ_MONTHS smallint,
    INDEX STATE_ID_INDEX (STATE_ID)
);

CREATE TABLE agency_table_type (
    AGENCY_TABLE_TYPE_ID smallint NOT NULL PRIMARY KEY,
    TABLE_NAME VARCHAR(50) NOT NULL,
    INDEX ID_INDEX (AGENCY_TABLE_TYPE_ID)
);

CREATE TABLE cde_agencies (
    DATA_YEAR INT NOT NULL,
    AGENCY_ID bigint NOT NULL,
    LEGACY_ORI character(9) NOT NULL,
    AGENCY_NAME text,
    SHORT_NAME text,
    AGENCY_TYPE_ID smallint NOT NULL,
    AGENCY_TYPE_NAME text,
    TRIBE_ID bigint,
    CAMPUS_ID bigint,
    CITY_ID bigint,
    CITY_NAME text,
    STATE_ID smallint NOT NULL,
    STATE_ABBR character(2) NOT NULL,
    PRIMARY_COUNTY_ID bigint,
    PRIMARY_COUNTY text,
    PRIMARY_COUNTY_FIPS character varying(5),
    AGENCY_STATUS character(1),
    SUBMITTING_AGENCY_ID bigint,
    SUBMITTING_SAI character varying(9),
    SUBMITTING_NAME text,
    SUBMITTING_STATE_ABBR character varying(2),
    START_YEAR smallint,
    DORMANT_YEAR smallint,
    CURRENT_YEAR smallint,
    REVISED_RAPE_START smallint,
    CURRENT_NIBRS_START_YEAR smallint,
    POPULATION bigint,
    POPULATION_GROUP_CODE character varying(2),
    POPULATION_GROUP_DESC text,
    POPULATION_SOURCE_FLAG character varying(1),
    SUBURBAN_AREA_FLAG character varying(1),
    CORE_CITY_FLAG character varying(1),
    MONTHS_REPORTED smallint,
    NIBRS_MONTHS_REPORTED smallint,
    PAST_10_YEARS_REPORTED smallint,
    COVERED_BY_ID bigint,
    COVERED_BY_ORI character(9),
    COVERED_BY_NAME character varying(100),
    STAFFING_YEAR smallint,
    TOTAL_OFFICERS integer,
    TOTAL_CIVILIANS integer,
    ICPSR_ZIP character(5),
    ICPSR_LAT numeric,
    ICPSR_LNG numeric,
    INDEX AGENCY_ID_INDEX (AGENCY_ID),
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    PRIMARY KEY (STATE_ID, DATA_YEAR, AGENCY_ID),
    CONSTRAINT CDE_AGENCIES_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE agency_participation (
    DATA_YEAR INT NOT NULL,
    STATE_ID smallint NOT NULL,
    AGENCY_PARTICIPATION_ID VARCHAR(36) NOT NULL,
    `YEAR` SMALLINT NOT NULL,
    STATE_NAME character varying(100),
    STATE_ABBR character varying(2),
    AGENCY_ID bigint NOT NULL,
    AGENCY_ORI character(9),
    AGENCY_NAME character varying(100),
    AGENCY_POPULATION bigint,
    POPULATION_GROUP_CODE character varying(2),
    POPULATION_GROUP character varying(150),
    REPORTED integer,
    MONTHS_REPORTED integer,
    NIBRS_REPORTED integer,
    NIBRS_MONTHS_REPORTED integer,
    COVERED integer,
    PARTICIPATED integer,
    NIBRS_PARTICIPATED integer,
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX AGENCY_PARTICIPATION_ID_INDEX (AGENCY_PARTICIPATION_ID),
    INDEX AGENCY_ID_INDEX (AGENCY_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, AGENCY_PARTICIPATION_ID),
    CONSTRAINT AGENCY_PARTICIPATION_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_month (
    STATE_ID smallint NOT NULL,
    NIBRS_MONTH_ID bigint NOT NULL,
    AGENCY_ID bigint NOT NULL,
    AGENCY_TABLE_TYPE_ID smallint NOT NULL,
    MONTH_NUM smallint NOT NULL,
    DATA_YEAR smallint NOT NULL,
    REPORTED_STATUS character varying(1),
    REPORT_DATE timestamp,
    PREPARED_DATE timestamp,
    UPDATE_FLAG character(1),
    ORIG_FORMAT character(1),
    FF_LINE_NUMBER bigint,
    DATA_HOME character varying(1),
    DDOCNAME character varying(50),
    DID bigint,
    INDEX NIBRS_MONTH_ID_INDEX (NIBRS_MONTH_ID),
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX AGENCY_ID_INDEX (AGENCY_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, NIBRS_MONTH_ID),
    CONSTRAINT NIBRS_MONTH_AGENCY_TABLE_TYPE_ID_FK FOREIGN KEY (AGENCY_TABLE_TYPE_ID) REFERENCES agency_table_type(AGENCY_TABLE_TYPE_ID),
    CONSTRAINT NIBRS_MONTH_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_cleared_except (
    CLEARED_EXCEPT_ID smallint NOT NULL PRIMARY KEY,
    CLEARED_EXCEPT_CODE character(1),
    CLEARED_EXCEPT_NAME character varying(100),
    INDEX CLEARED_EXCEPT_ID_INDEX (CLEARED_EXCEPT_ID)
);

CREATE TABLE nibrs_incident (
    STATE_ID smallint NOT NULL,
    DATA_YEAR int NOT NULL,
    AGENCY_ID bigint NOT NULL,
    AGENCY_TABLE_TYPE_ID smallint NOT NULL,
    INCIDENT_ID bigint NOT NULL,
    NIBRS_MONTH_ID bigint NOT NULL,
    INCIDENT_NUMBER character varying(15),
    CARGO_THEFT_FLAG character varying(1),
    SUBMISSION_DATE timestamp,
    INCIDENT_DATE timestamp,
    REPORT_DATE_FLAG character varying(1),
    INCIDENT_HOUR smallint,
    CLEARED_EXCEPT_ID smallint NOT NULL,
    CLEARED_EXCEPT_DATE timestamp,
    INCIDENT_STATUS smallint,
    DATA_HOME character(1),
    DDOCNAME character varying(100),
    ORIG_FORMAT character(1),
    FF_LINE_NUMBER bigint,
    DID bigint,
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX INCIDENT_ID_INDEX (INCIDENT_ID),
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX AGENCY_ID_INDEX (AGENCY_ID),
    INDEX NIBRS_MONTH_ID_INDEX (NIBRS_MONTH_ID),
    INDEX CLEARED_EXCEPT_ID_INDEX (CLEARED_EXCEPT_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, INCIDENT_ID),
    CONSTRAINT NIBRS_INCIDENT_AGENCY_TABLE_TYPE_ID_FK FOREIGN KEY (AGENCY_TABLE_TYPE_ID) REFERENCES agency_table_type(AGENCY_TABLE_TYPE_ID),
    CONSTRAINT NIBRS_INCIDENT_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_arrest_type (
    ARREST_TYPE_ID smallint NOT NULL PRIMARY KEY,
    ARREST_TYPE_CODE character(1),
    ARREST_TYPE_NAME character varying(100),
    INDEX ARREST_TYPE_ID_INDEX (ARREST_TYPE_ID)
);

CREATE TABLE nibrs_offense_type (
    OFFENSE_TYPE_ID bigint NOT NULL PRIMARY KEY,
    OFFENSE_CODE character varying(5),
    OFFENSE_NAME character varying(100),
    CRIME_AGAINST character varying(100),
    CT_FLAG character(1),
    HC_FLAG character(1),
    HC_CODE character varying(5),
    OFFENSE_CATEGORY_NAME character varying(100),
    INDEX OFFENSE_TYPE_ID_INDEX (OFFENSE_TYPE_ID)
);

CREATE TABLE nibrs_age (
    AGE_ID smallint NOT NULL PRIMARY KEY,
    AGE_CODE character(2),
    AGE_NAME character varying(100),
    INDEX AGE_ID_INDEX (AGE_ID)
);

CREATE TABLE ref_race (
    RACE_ID smallint NOT NULL PRIMARY KEY,
    RACE_CODE character varying(2) NOT NULL,
    RACE_DESC character varying(100) NOT NULL,
    SORT_ORDER smallint,
    START_YEAR smallint,
    END_YEAR smallint,
    NOTES character varying(1000),
    INDEX RACE_ID_INDEX (RACE_ID)
);

CREATE TABLE nibrs_ethnicity (
    ETHNICITY_ID smallint NOT NULL PRIMARY KEY,
    ETHNICITY_CODE character(1),
    ETHNICITY_NAME character varying(100),
    HC_FLAG character varying(1) DEFAULT 'Y',
    INDEX ETHNICITY_ID_INDEX (ETHNICITY_ID)
);

CREATE TABLE nibrs_arrestee (
    STATE_ID smallint NOT NULL,
    DATA_YEAR int,
    ARRESTEE_ID bigint NOT NULL,
    INCIDENT_ID bigint NOT NULL,
    ARRESTEE_SEQ_NUM bigint,
    ARREST_NUM character varying(12),
    ARREST_DATE timestamp,
    ARREST_TYPE_ID smallint,
    MULTIPLE_INDICATOR character(1),
    OFFENSE_TYPE_ID bigint NOT NULL,
    AGE_ID smallint NOT NULL,
    AGE_NUM smallint,
    SEX_CODE character(1),
    RACE_ID smallint NOT NULL,
    ETHNICITY_ID smallint,
    RESIDENT_CODE character(1),
    UNDER_18_DISPOSITION_CODE character(1),
    CLEARANCE_IND character(1),
    FF_LINE_NUMBER bigint,
    AGE_RANGE_LOW_NUM smallint,
    AGE_RANGE_HIGH_NUM smallint,
    INDEX ARRESTEE_ID_INDEX (ARRESTEE_ID),
    INDEX INCIDENT_ID_INDEX (INCIDENT_ID),
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX ARREST_TYPE_ID_INDEX (ARREST_TYPE_ID),
    INDEX OFFENSE_TYPE_ID_INDEX (OFFENSE_TYPE_ID),
    INDEX ETHNICITY_ID_INDEX (ETHNICITY_ID),
    INDEX AGE_ID_INDEX (AGE_ID),
    INDEX RACE_ID_INDEX (RACE_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, ARRESTEE_ID),
    CONSTRAINT NIBRS_ARRESTEE_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_weapon_type (
    WEAPON_ID smallint NOT NULL PRIMARY KEY,
    WEAPON_CODE character varying(3),
    WEAPON_NAME character varying(100),
    SHR_FLAG character(1),
    INDEX WEAPON_ID_INDEX (WEAPON_ID)
);

CREATE TABLE nibrs_arrestee_weapon (
    STATE_ID smallint NOT NULL,
    DATA_YEAR int NOT NULL,
    ARRESTEE_ID bigint NOT NULL,
    WEAPON_ID smallint NOT NULL,
    NIBRS_ARRESTEE_WEAPON_ID bigint NOT NULL,
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX ARRESTEE_ID_INDEX (ARRESTEE_ID),
    INDEX WEAPON_ID_INDEX (WEAPON_ID),
    INDEX NIBRS_ARRESTEE_WEAPON_ID_INDEX (NIBRS_ARRESTEE_WEAPON_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, NIBRS_ARRESTEE_WEAPON_ID),
    CONSTRAINT NIBRS_ARRESTEE_WEAPON_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_bias_list (
    BIAS_ID smallint NOT NULL PRIMARY KEY,
    BIAS_CODE character(2),
    BIAS_NAME character varying(100),
    INDEX BIAS_ID_INDEX (BIAS_ID)
);

CREATE TABLE nibrs_location_type (
    LOCATION_ID bigint NOT NULL PRIMARY KEY,
    LOCATION_CODE character(2),
    LOCATION_NAME character varying(100),
    INDEX LOCATION_ID_INDEX (LOCATION_ID)
);

CREATE TABLE nibrs_offense (
    STATE_ID smallint NOT NULL,
    DATA_YEAR int NOT NULL,
    OFFENSE_ID bigint NOT NULL,
    INCIDENT_ID bigint NOT NULL,
    OFFENSE_TYPE_ID bigint NOT NULL,
    ATTEMPT_COMPLETE_FLAG character(1),
    LOCATION_ID bigint NOT NULL,
    NUM_PREMISES_ENTERED smallint,
    METHOD_ENTRY_CODE character(1),
    FF_LINE_NUMBER bigint,
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX INCIDENT_ID_INDEX (INCIDENT_ID),
    INDEX OFFENSE_ID_INDEX (OFFENSE_ID),
    INDEX OFFENSE_TYPE_ID_INDEX (OFFENSE_TYPE_ID),
    INDEX LOCATION_ID_INDEX (LOCATION_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, OFFENSE_ID),
    CONSTRAINT NIBRS_OFFENSE_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_bias_motivation (
    STATE_ID smallint NOT NULL,
    NIBRS_BIAS_MOTIVATION_ID VARCHAR(36) NOT NULL,
    DATA_YEAR int NOT NULL,
    BIAS_ID smallint NOT NULL,
    OFFENSE_ID bigint NOT NULL,
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX NIBRS_BIAS_MOTIVATION_ID (NIBRS_BIAS_MOTIVATION_ID),
    INDEX BIAS_ID_INDEX (BIAS_ID),
    INDEX OFFENSE_ID_INDEX (OFFENSE_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, NIBRS_BIAS_MOTIVATION_ID),
    CONSTRAINT NIBRS_BIAS_MOTIVATION_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_offender (
    STATE_ID smallint NOT NULL,
    DATA_YEAR int NOT NULL,
    OFFENDER_ID bigint NOT NULL,
    INCIDENT_ID bigint NOT NULL,
    OFFENDER_SEQ_NUM smallint,
    AGE_ID smallint,
    AGE_NUM smallint,
    SEX_CODE character(1),
    RACE_ID smallint,
    ETHNICITY_ID smallint,
    FF_LINE_NUMBER bigint,
    AGE_RANGE_LOW_NUM smallint,
    AGE_RANGE_HIGH_NUM smallint,
    INDEX OFFENDER_ID_INDEX (OFFENDER_ID),
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX INCIDENT_ID_INDEX (INCIDENT_ID),
    INDEX AGE_ID_INDEX (AGE_ID),
    INDEX RACE_ID_INDEX (RACE_ID),
    INDEX ETHNICITY_ID_INDEX (ETHNICITY_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, OFFENDER_ID),
    CONSTRAINT NIBRS_OFFENDER_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_prop_loss_type (
    PROP_LOSS_ID smallint NOT NULL PRIMARY KEY,
    PROP_LOSS_NAME character varying(100),
    INDEX PROP_LOSS_ID_INDEX (PROP_LOSS_ID)
);

CREATE TABLE nibrs_property (
    STATE_ID smallint NOT NULL,
    DATA_YEAR int NOT NULL,
    PROPERTY_ID bigint NOT NULL PRIMARY KEY,
    INCIDENT_ID bigint NOT NULL,
    PROP_LOSS_ID smallint NOT NULL,
    STOLEN_COUNT smallint,
    RECOVERED_COUNT smallint,
    FF_LINE_NUMBER bigint,
    INDEX PROPERTY_ID_INDEX (PROPERTY_ID),
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX INCIDENT_ID_INDEX (INCIDENT_ID),
    INDEX PROP_LOSS_ID_INDEX (PROP_LOSS_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, PROPERTY_ID),
    CONSTRAINT NIBRS_PROPERTY_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_prop_desc_type (
    PROP_DESC_ID smallint NOT NULL PRIMARY KEY,
    PROP_DESC_CODE character(2),
    PROP_DESC_NAME character varying(100),
    INDEX PROP_DESC_ID_INDEX (PROP_DESC_ID)
);

CREATE TABLE nibrs_property_desc (
    STATE_ID smallint NOT NULL,
    DATA_YEAR int NOT NULL,
    PROPERTY_ID bigint NOT NULL,
    PROP_DESC_ID smallint NOT NULL,
    PROPERTY_VALUE bigint,
    DATE_RECOVERED timestamp,
    NIBRS_PROP_DESC_ID VARCHAR(36) NOT NULL,
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX PROPERTY_ID_INDEX (PROPERTY_ID),
    INDEX PROP_DESC_ID_INDEX (PROP_DESC_ID),
    INDEX NIBRS_PROP_DESC_ID_INDEX (NIBRS_PROP_DESC_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, NIBRS_PROP_DESC_ID),
    CONSTRAINT NIBRS_PROPERTY_DESC_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_using_list (
    SUSPECT_USING_ID smallint NOT NULL PRIMARY KEY,
    SUSPECT_USING_CODE character(1),
    SUSPECT_USING_NAME character varying(100),
    INDEX SUSPECT_USING_ID_INDEX (SUSPECT_USING_ID)
);

CREATE TABLE nibrs_suspect_using (
    STATE_ID smallint NOT NULL,
    DATA_YEAR int NOT NULL,
    NIBRS_SUSPECT_USING_ID VARCHAR(36) NOT NULL,
    SUSPECT_USING_ID smallint NOT NULL,
    OFFENSE_ID bigint NOT NULL,
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX NIBRS_SUSPECT_USING_ID_INDEX (NIBRS_SUSPECT_USING_ID),
    INDEX SUSPECT_USING_ID_INDEX (SUSPECT_USING_ID),
    INDEX OFFENSE_ID_INDEX (OFFENSE_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, NIBRS_SUSPECT_USING_ID),
    CONSTRAINT NIBRS_SUSPECT_USING_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_suspected_drug_type (
    SUSPECTED_DRUG_TYPE_ID smallint NOT NULL PRIMARY KEY,
    SUSPECTED_DRUG_CODE character(1),
    SUSPECTED_DRUG_NAME character varying(100),
    INDEX SUSPECTED_DRUG_TYPE_ID_INDEX (SUSPECTED_DRUG_TYPE_ID)
);

CREATE TABLE nibrs_drug_measure_type (
    DRUG_MEASURE_TYPE_ID smallint NOT NULL PRIMARY KEY,
    DRUG_MEASURE_CODE character(2),
    DRUG_MEASURE_NAME character varying(100),
    INDEX DRUG_MEASURE_TYPE_ID_INDEX (DRUG_MEASURE_TYPE_ID)
);

CREATE TABLE nibrs_suspected_drug (
    STATE_ID smallint NOT NULL,
    DATA_YEAR int NOT NULL,
    SUSPECTED_DRUG_TYPE_ID smallint NOT NULL,
    PROPERTY_ID bigint NOT NULL,
    EST_DRUG_QTY double precision,
    DRUG_MEASURE_TYPE_ID smallint,
    NIBRS_SUSPECTED_DRUG_ID bigint NOT NULL,
    INDEX NIBRS_SUSPECTED_DRUG_ID_INDEX (NIBRS_SUSPECTED_DRUG_ID),
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX SUSPECTED_DRUG_TYPE_ID_INDEX (SUSPECTED_DRUG_TYPE_ID),
    INDEX PROPERTY_ID_INDEX (PROPERTY_ID),
    INDEX DRUG_MEASURE_TYPE_ID_INDEX (DRUG_MEASURE_TYPE_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, NIBRS_SUSPECTED_DRUG_ID),
    CONSTRAINT NIBRS_SUSPECTED_DRUG_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_victim_type (
    VICTIM_TYPE_ID smallint NOT NULL PRIMARY KEY,
    VICTIM_TYPE_CODE character(1),
    VICTIM_TYPE_NAME character varying(100),
    INDEX VICTIM_TYPE_ID_INDEX (VICTIM_TYPE_ID)
);

CREATE TABLE nibrs_assignment_type (
    ASSIGNMENT_TYPE_ID smallint NOT NULL PRIMARY KEY,
    ASSIGNMENT_TYPE_CODE character(1),
    ASSIGNMENT_TYPE_NAME character varying(100),
    INDEX ASSIGNMENT_TYPE_ID_INDEX (ASSIGNMENT_TYPE_ID)
);

CREATE TABLE nibrs_activity_type (
    ACTIVITY_TYPE_ID smallint NOT NULL PRIMARY KEY,
    ACTIVITY_TYPE_CODE character(2),
    ACTIVITY_TYPE_NAME character varying(100),
    INDEX ACTIVITY_TYPE_ID_INDEX (ACTIVITY_TYPE_ID)
);

CREATE TABLE nibrs_victim (
    STATE_ID smallint NOT NULL,
    DATA_YEAR int NOT NULL,
    VICTIM_ID bigint NOT NULL,
    INCIDENT_ID bigint NOT NULL,
    VICTIM_SEQ_NUM smallint,
    VICTIM_TYPE_ID smallint,
    ASSIGNMENT_TYPE_ID smallint,
    ACTIVITY_TYPE_ID smallint,
    OUTSIDE_AGENCY_ID bigint,
    AGE_ID smallint,
    AGE_NUM smallint,
    SEX_CODE character(1),
    RACE_ID smallint,
    ETHNICITY_ID smallint,
    RESIDENT_STATUS_CODE character(1),
    AGENCY_DATA_YEAR smallint,
    FF_LINE_NUMBER bigint,
    AGE_RANGE_LOW_NUM smallint,
    AGE_RANGE_HIGH_NUM smallint,
    INDEX VICTIM_ID_INDEX (VICTIM_ID),
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX INCIDENT_ID_INDEX (INCIDENT_ID),
    INDEX VICTIM_TYPE_ID_INDEX (VICTIM_TYPE_ID),
    INDEX ASSIGNMENT_TYPE_ID_INDEX (ASSIGNMENT_TYPE_ID),
    INDEX ACTIVITY_TYPE_ID_INDEX (ACTIVITY_TYPE_ID),
    INDEX AGE_ID_INDEX (AGE_ID),
    INDEX RACE_ID_INDEX (RACE_ID),
    INDEX ETHNICITY_ID_INDEX (ETHNICITY_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, VICTIM_ID),
    CONSTRAINT NIBRS_VICTIM_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_injury (
    INJURY_ID smallint NOT NULL PRIMARY KEY,
    INJURY_CODE character(1),
    INJURY_NAME character varying(100),
    INDEX INJURY_ID_INDEX (INJURY_ID)
);

CREATE TABLE nibrs_victim_injury (
    STATE_ID smallint NOT NULL,
    DATA_YEAR int NOT NULL,
    NIBRS_VICTIM_INJURY_ID VARCHAR(36) NOT NULL,
    VICTIM_ID bigint NOT NULL,
    INJURY_ID smallint NOT NULL,
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX NIBRS_VICTIM_INJURY_ID_INDEX (NIBRS_VICTIM_INJURY_ID),
    INDEX VICTIM_ID_INDEX (VICTIM_ID),
    INDEX INJURY_ID_INDEX (INJURY_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, NIBRS_VICTIM_INJURY_ID),
    CONSTRAINT NIBRS_VICTIM_INJURY_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_relationship (
    RELATIONSHIP_ID smallint NOT NULL PRIMARY KEY,
    RELATIONSHIP_CODE character(2),
    RELATIONSHIP_NAME character varying(100),
    INDEX RELATIONSHIP_ID_INDEX (RELATIONSHIP_ID)
);

CREATE TABLE nibrs_victim_offender_rel (
    STATE_ID smallint NOT NULL,
    DATA_YEAR int NOT NULL,
    VICTIM_ID bigint NOT NULL,
    OFFENDER_ID bigint NOT NULL,
    RELATIONSHIP_ID smallint NOT NULL,
    NIBRS_VICTIM_OFFENDER_ID bigint NOT NULL,
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX VICTIM_ID_INDEX (VICTIM_ID),
    INDEX OFFENDER_ID_INDEX (OFFENDER_ID),
    INDEX RELATIONSHIP_ID_INDEX (RELATIONSHIP_ID),
    INDEX NIBRS_VICTIM_OFFENDER_ID_INDEX (NIBRS_VICTIM_OFFENDER_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, NIBRS_VICTIM_OFFENDER_ID),
    CONSTRAINT NIBRS_VICTIM_OFFENDER_REL_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_victim_offense (
    STATE_ID smallint NOT NULL,
    DATA_YEAR int NOT NULL,
    NIBRS_VICTIM_OFFENSE_ID VARCHAR(36) NOT NULL,
    VICTIM_ID bigint NOT NULL,
    OFFENSE_ID bigint NOT NULL,
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX NIBRS_VICTIM_OFFENSE_ID_INDEX (NIBRS_VICTIM_OFFENSE_ID),
    INDEX VICTIM_ID_INDEX (VICTIM_ID),
    INDEX OFFENSE_ID_INDEX (OFFENSE_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, NIBRS_VICTIM_OFFENSE_ID),
    CONSTRAINT NIBRS_VICTIM_OFFENSE_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_criminal_act_type (
    CRIMINAL_ACT_ID smallint NOT NULL PRIMARY KEY,
    CRIMINAL_ACT_CODE character(1),
    CRIMINAL_ACT_NAME character varying(100),
    INDEX CRIMINAL_ACT_ID_INDEX (CRIMINAL_ACT_ID)
);

CREATE TABLE nibrs_criminal_act (
    STATE_ID smallint NOT NULL,
    DATA_YEAR int NOT NULL,
    NIBRS_CRIMINAL_ACT_ID VARCHAR(36) NOT NULL,
    CRIMINAL_ACT_ID smallint NOT NULL,
    OFFENSE_ID bigint NOT NULL,
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX NIBRS_CRIMINAL_ACT_ID_INDEX (NIBRS_CRIMINAL_ACT_ID),
    INDEX CRIMINAL_ACT_ID_INDEX (CRIMINAL_ACT_ID),
    INDEX OFFENSE_ID_INDEX (OFFENSE_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, NIBRS_CRIMINAL_ACT_ID),
    CONSTRAINT NIBRS_CRIMINAL_ACT_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_weapon (
    STATE_ID smallint NOT NULL,
    DATA_YEAR int,
    WEAPON_ID smallint NOT NULL,
    OFFENSE_ID bigint NOT NULL,
    NIBRS_WEAPON_ID bigint NOT NULL,
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX WEAPON_ID_INDEX (WEAPON_ID),
    INDEX OFFENSE_ID_INDEX (OFFENSE_ID),
    INDEX NIBRS_WEAPON_ID_INDEX (NIBRS_WEAPON_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, NIBRS_WEAPON_ID),
    CONSTRAINT NIBRS_WEAPON_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);

CREATE TABLE nibrs_circumstances (
    CIRCUMSTANCES_ID smallint NOT NULL PRIMARY KEY,
    CIRCUMSTANCES_TYPE character(1),
    CIRCUMSTANCES_CODE smallint,
    CIRCUMSTANCES_NAME character varying(100),
    INDEX CIRCUMSTANCES_ID_INDEX (CIRCUMSTANCES_ID)
);

CREATE TABLE nibrs_justifiable_force (
    JUSTIFIABLE_FORCE_ID smallint NOT NULL PRIMARY KEY,
    JUSTIFIABLE_FORCE_CODE character(1),
    JUSTIFIABLE_FORCE_NAME character varying(100),
    INDEX JUSTIFIABLE_FORCE_ID_INDEX (JUSTIFIABLE_FORCE_ID)
);

CREATE TABLE nibrs_victim_circumstances (
    STATE_ID smallint NOT NULL,
    DATA_YEAR int NOT NULL,
    NIBRS_VICTIM_CIRCUMSTANCES_ID VARCHAR(36) NOT NULL,
    VICTIM_ID bigint NOT NULL,
    CIRCUMSTANCES_ID smallint NOT NULL,
    JUSTIFIABLE_FORCE_ID smallint,
    INDEX STATE_ID_INDEX (STATE_ID),
    INDEX DATA_YEAR_INDEX (DATA_YEAR),
    INDEX NIBRS_VICTIM_CIRCUMSTANCES_ID_INDEX (NIBRS_VICTIM_CIRCUMSTANCES_ID),
    INDEX VICTIM_ID_INDEX (VICTIM_ID),
    INDEX CIRCUMSTANCES_ID_INDEX (CIRCUMSTANCES_ID),
    INDEX JUSTIFIABLE_FORCE_ID_INDEX (JUSTIFIABLE_FORCE_ID),
    PRIMARY KEY (STATE_ID, DATA_YEAR, NIBRS_VICTIM_CIRCUMSTANCES_ID),
    CONSTRAINT NIBRS_VICTIM_CIRCUMSTANCES_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES ref_state(STATE_ID)
);
