

def get_data_url(ticker: str):
    return '{}/{}.{}'.format(BASE_PATH, ticker, POSTFIX)

POSTFIX = 'csv'
BASE_PATH = 'https://coinmetrics.io/newdata'
COINLIST = ['zrx',
            'elf',
            'ae',
            'aion',
            'ant',
            'rep',
            'bat',
            'bnb',
            'bnb_mainnet',
            'bch',
            'btg',
            'bsv',
            'btc',
            'btm',
            'ada',
            'link',
            'cvc',
            'dai',
            'dash',
            'mana',
            'dcr',
            'dgb',
            'doge',
            'drgn',
            'eng',
            'eos',
            'eos_eth',
            'etc',
            'eth',
            'ethos',
            'fun',
            'gas',
            'gusd',
            'gno',
            'gnt',
            'grin',
            'ht',
            'icx',
            'kcs',
            'knc',
            'lsk',
            'ltc',
            'loom',
            'lrc',
            'maid',
            'mkr',
            'xmr',
            'nas',
            'xem',
            'neo',
            'omg',
            'pax',
            'pivx',
            'poly',
            'ppt',
            'powr',
            'qash',
            'qtum',
            'snt',
            'xlm',
            'pay',
            'usdt_eth',
            'usdt',
            'xtz',
            'trx',
            'tusd',
            'leo_eth',
            'leo_eos',
            'usdc',
            'vet',
            'xvg',
            'vtc',
            'wtc',
            'waves',
            'xrp',
            'zec',
            'zil']